language: python
sudo: false
python:
  - "3.4"

install:
  - pip install -U twine
  - make install
  - ./env/bin/pip install coveralls

script:
  - make checkstyle
  - make test

after_success:
  - ./env/bin/coveralls

deploy:
- provider: pypi
  user: marvinpinto
  password:
    secure: "HFA7+WaDvbNfrDWeEMS3W9exUtTKhtnDxyuDF7W956bbFD/iMrmTL83x6rsuHY1/Aehdi18A14ses00weYov2T6U6fvOx1j8BIREq1PawIq4iqVnRYGDi5bTsA807gJXpPGobjQUAqCRNjdB9Pj1S8i2Hru68vddEaGtJFYVuRLOInD/73yE4IJEpfpCul5AmHHZIVajnfQ5YTV9XYru87JBd7AS+zkfnXvPCPLL88LtUhmuOAwGbDNtBbXTyQ7SGTztJzsQABSksctsoolJpHUrMzGGVV0svoX7zRzKghHCFB+46RZoQLbGlcLb90xZiDvjnPBYIRl21m3LZOx7hIB51eU3s+3Egk/R+wc7v+Cl76wYU2OErWUYmHQWSyacyBXXx/DAqRMuOFWUzfb+qG0vrIABW6gjicOGJgbmlTVxtMbsHyPlxrBac3e3o5xaH9yh0VGUoOGuNP6WW1OiO6a09OH+T8PopDwPC82WHwL1+CiHj93NnW6zG4MNX4nUnnILT7njbe6we1MTFJkNdq9EoNNQcTfsbwqiJoBRWwNB1PSxrI3h/Nn2Dv3bKe7jmeFATXxu7K76peAhxx7mnyAdU3/JvZZ2ttL7J1E9w9twDungzPSQRMjiliIjMekkSAep5OnervxtP6yEQUoxZkegmYjMAqVL6rr+7FkEGsg="
  on:
    tags: true
    repo: marvinpinto/charlesbot-pagerduty

notifications:
  email: false
  irc:
    - secure: "YWwd05QyfGMGNdEK0Mbp/DmyerfgjjMYL3KmD8jK9UKcNtEsepFFxM1Uyu+BHECXkOwvXd3pN70pKe5AmKw2baA2fjBikzDQXa6zILXDiikHpaRrtjlYxkEQ7xo0W4TjifZWIJi/X7CsuuH3fpnu1xqpPbMYQeVzlCa2s/X/MqXgpwkwyfa9aEVTGtSZIcBdPrkF8mebd8DCOmickyktAQlu+waBOC8NTOMdtjl1s8RcPy4x9sbimhgoYSZEpZAqT+girse6/zk7t0A6dZL2AQwWtEVpek2KxbrfFSP5jtfLWatqcKM6V7ANhqyWzL2ORlWfkYpnaIawMJLwAA7DslIkKX6bte3TGY+Lk/LnsvdKTRnaJqudAU2UNPwXcPoTOVsSUzauQycHtEdth9gsz54OCDlc/Hw+8Ttzvf0fM/yt8X6HTqtjjL/+XKcDQLk7izkqX62Q14XgFH+yv9IUTVkAwfArDnmDuHwPh1YoP1Exu1ifM+BMh/167gMOaQVTCd3KYP1BRMALb5hcUBjaKpTyeBXvI0N/WU3u88yifzW0ZDELSrbMQ9F1GYIXLQwULOUvw7cg93VZqjXtx4zHU2FlYcJnHOtsMU2qdrdVRYO9xSvgemoMESUKC5FIj58dGHHxcP3n+qyQgDlJ6E3O5FcaVNSOMBgQ0IL9m/lH8Rg="
